.travis.yml, package-lock.json, package.json
=> Initialize Repository

script/seed.js
=> Seed branch issue#8

package-lock.json, package.json, server/db/models/Order.js, server/db/models/Product.js, server/db/models/Review.js, tests/category.spec.js, tests/index.spec.js, tests/order.spec.js, tests/product.spec.js, tests/review.spec.js
=> Testing models 9

client/components/AllProducts.js, client/components/AllProducts.spec.js, client/components/SingleProduct.js, client/components/SingleProduct.spec.js, client/store/category.js, client/store/index.js, client/store/product.js, server/api/category.js, server/api/index.js, server/api/products.js
=> Category search 5

server/db/models/User.spec.js, server/db/models/index.js
=> case sensitive issues resolved

server/auth/index.js, server/db/models/index.js
=> Fix casing in user model filename

script/seed.js
=> added seed products

client/components/AllProducts.js, client/store/product.js, server/api/products.js
=> delete product button added for admin users on all products page

tests/AllProducts.spec.js
=> tests for delete product feature

client/components/AddCategory.js, client/components/AllProducts.js, client/components/CategoryFormRedux.js, client/components/EditCategory.js, client/components/index.js, client/routes.js, client/store/category.js, package-lock.json, server/api/category.js, tests/AllProducts.spec.js
=> Add edit categories

client/components/AddCategory.js, package-lock.json
=> Fixreduxform

client/components/AllProducts.js, client/components/SingleProduct.js, client/routes.js, client/store/cart.js, client/utils/ProductToken.js, client/utils/localStorage.js
=> Add item to cart issue#43

server/db/models/Order.js, server/db/models/OrderItems.js, server/db/models/ShippingInfo.js, server/db/models/index.js
=> Update Models To Include OrderItem and Shipping Info

client/components/CartItem.js, client/components/CartView.js, client/store/cart.js, server/api/orders.js
=> Cart functionality issue#64

client/components/Review.js, client/components/ReviewReduxForm.js, client/components/SingleProduct.js, client/store/index.js, client/store/reviews.js, package-lock.json, server/api/index.js, server/api/reviews.js
=> finished reviews

package-lock.json, package.json
=> fixed testing issue

client/components/CartItem.js, client/store/cart.js, server/api/orders.js
=> Cart view and items issue#67

client/store/cart.js, server/db/models/Product.js
=> add to cart fully debugged

client/store/index.js, client/store/product.js, client/store/shippinginfo.js
=> creates redux store for shipping info

script/seed.js, server/api/category.js, server/api/index.js, server/api/orders.js, server/api/products.js, server/api/reviews.js, server/api/shippingInfo.js, server/api/users.js, server/api/users.spec.js, server/api/validations.js
=> updates routes with more protection for users and admins only

client/components/EditCategory.js, client/store/category.js, script/seed.js
=> handles delete categories

client/components/AddShippingInfo.js, client/routes.js, package-lock.json, package.json, server/api/orders.js
=> creating an order

client/components/AddShippingInfo.js, client/components/Checkout.js, client/components/OrderSummary.js, client/components/stripe.js, client/store/orders.js, package-lock.json
=> Order summary

package-lock.json
just changed the package-lock.json file to match with the previous master branch
=> fixed package-lock.json file merge conflicts

client/components/OrderAdmin.js, client/components/SingleOrder.js, client/store/orders.js, server/api/orders.js
=> orders admin complete

client/components/SingleProduct.js
Added a header 'no reviews yet' if there are no reviews for a particular product
=> minor edits

client/components/AddShippingInfo.js, client/store/orders.js, server/api/charges.js, server/api/shippingInfo.js
=> key fix and bug fix

.gitignore, client/components/SingleOrder.js, client/store/orders.js, package-lock.json, package.json, server/api/orders.js, server/index.js
=> re-adds order summary

server/email.js
=> heroku updates

client/components/AllProducts.js, client/components/AllProductsList.js, client/components/Review.js, client/components/SingleProduct.js, client/components/navbar.js, client/routes.js
=> final edits
